= Flight Controller Development Board

This project is a development board intended for flight algorithm design. The intention is to create a board that can plug into multiple different vehicle structures, e.g.

* Quadcopter
* Helicopter
* Fixed-wing

= "User requirements"/Purpose

The purpose is to provide a platform for experimenting with algorithms for take-off, landing, and stabilising (initially) quadcopters. Later, the board should be sufficiently flexible to either expand to other flight form factors or investigate more complex algorithms.

There should be a CPU with sufficient processing power for basic algorithms and an FPGA to support a variety of computationally-intensive/ML-based algorithms. The FPGA should be interfaced to the CPU as a co-processor.

The board should contain battery and power management, should be chargeable using USB-C, and should provide drive/control circuitry for up to four motors and up to four flight control surfaces. The drive method should be capable of interfacing to a variety of motors, without changing the development board hardware. 

The board should contain location/motion sensors for providing closed-loop input to the flight control algorithms.

There should be support WiFi and Bluetooth connectivity for basic control, and should support extending for RF-based remote control. This anticipates initial experiments mainly targeting the closed loop control algorithms, have minimal external input. Full flight testing (involving longer range communication) is a later step

SPI/I2C/UART and general GPIO connections should be available for interfacing additional modules to the flight controller later, to make the platform adaptable as requirements change.

= Similar Boards

* STMicroelectronics sells a https://www.st.com/en/evaluation-tools/steval-fcu001v1.html[flight control evaluation board] which is similar to the proposed design. It can be used as a reference for the basic aspects of the design.
* https://holybro.com/products/kakute-f722[Kakute F722 Flight Controller] is a small (8 g), cheap, board which is based around an STM32F7 MCU, with support for multiple peripherals including sensor inputs and motor drives. The flight controller is used in https://sites.bu.edu/uav/first-build/step1/[This design guide], which also uses the https://holybro.com/products/tekko32-f4-4in1-50a-esc[Tekko32 F4 4in1 50A ESC] (supports four motors, 13.8 g). 


= Specification

The detailed specifications are outlined below.
