= All-In-One Flight Controller Development Board

*Integrated flight controller, electronic speed controller and server controller, and power management board.*

This project is a development board intended for flight algorithm design. The overall design goals are:

* 🚀 Generous processing power to investigate a wide range of flight control methods and algorithms.
* 📡 Barometric pressure (altitude), GPS, accelerometer (motion), and magnetometer (compass) sensors.
* 🛜 WiFi and Bluetooth support for simple communication/experimentation.
* 📻 Radio control with minimum four channels supporting standard protocols. 
* 🔋 Full battery management including USB-C charging for LiPo batteries.
* 📷 Built-in HD camera support, for algorithm use and for sending back to base.
* ➕ A range of peripherals such as I2C/SPI/UART for expansion modules.
* 🚁 Future versions to plug into fixed-wing and helicopter remote control vehicles.

= "User requirements"/Purpose

The purpose is to provide a platform for experimenting with algorithms for take-off, landing, and stabilising (initially) quadcopters. Later, the board should be sufficiently flexible to either expand to other flight form factors or investigate more complex algorithms. However, due to the range of different form factors for flying vehicles, we will not explicitly design this functionality in the first version -- just keep an eye on the bigger picture.

The CPU should have sufficient processing power for basic algorithms and an FPGA co-processor will provide flexibility for custom high-performance algorithms not suited to the CPU.

The camera input is intended to capture first-person images from the flight and send them back to the base. However, it is anticipated that the images may also be used in the flight algorithms (obstacle detection, tracking, etc.) and the associated image-processing algorithms may be suited for FPGA implementation.

The board should contain battery and power management, should be chargeable using USB-C, and should provide drive/control circuitry for up to four motors and up to four flight control surfaces. Flight control surfaces are not necessary for the quadcopter, but including them would enable the unit to be repurposed to control fixed-wing vehicles without too much additional effort.

Only three-phase brush-less sensor-less motors will be used in the first version of the board. These are more efficient and more robust than the brushed alternative, and sensor-less operation is sufficient given the high speed of the motors.

The board should contain location/motion sensors for providing closed-loop input to the flight control algorithms, and any other purposes.

There should be support WiFi and Bluetooth connectivity for basic control, and should support extending for RF-based remote control. This anticipates initial experiments mainly targeting the closed loop control algorithms, having minimal external input (likely over a short range, in a WiFi environment). Full flight testing (involving longer range communication) is a second step.

SPI/I2C/UART and general GPIO connections should be available for interfacing additional modules to the flight controller later, to make the platform adaptable as requirements change.

= Similar Boards

* STMicroelectronics sells a https://www.st.com/en/evaluation-tools/steval-fcu001v1.html[flight control evaluation board] which is similar to the proposed design. It can be used as a reference for the basic aspects of the design.
* https://holybro.com/products/kakute-f722[Kakute F722 Flight Controller] is a small (8 g), cheap, board which is based around an STM32F7 MCU, with support for multiple peripherals including sensor inputs and motor drives. The flight controller is used in https://sites.bu.edu/uav/first-build/step1/[This design guide], which also uses the https://holybro.com/products/tekko32-f4-4in1-50a-esc[Tekko32 F4 4in1 50A ESC] (supports four motors, 13.8 g). 

= Overall Architecture

This design combines the responsibilities normally assigned to separate flight controller board, an electronic speed controller, and a power supply board. The intention is that the result is easy to use and can form the basis for a simple quadcopter design.




= Detailed Specification

The detailed specifications are outlined below.
