= Brushless DC Motor Control using STM32F746

This experiment is intended to establish whether PWM from general-purpose timers can control multiple BLDC motors. The results should decide whether it is feasible to perform all the motor control logic in a single MCU such as the STM32H747, which only has 2 advanced motor control timers, but has 10 general purpose timers. The advantages of using a single MCU is board simplicity, lower cost, and lower programming and flashing complexity. The disadvantage is any specific deficiencies with using general timers for three-phase PWM, and CPU conflict/contention running multiple motors on one CPU (this seems unlikely given how "slow" the motor control is, but it is worth checking).

== Theory/Simulation

The T-Motor P1604 3800KV motor used in this experiment is a three-phase motor. A clear diagram of the configuration of this type of motor is Figure 1 in xref:../../references/appnote-brushless-dc-motor-control.pdf[this Microchip application note]. Each opposite pair of windings is arranged in series, and is wired to the adjacent pairs in such a way that when current flows in one phase and out the other, the rotor is statically held in between the two pairs of windings.

The simplest method to drive the motor is to sequentially excite pairs of phases to progress the rotor around each of the 6 static positions. Provided that the commutation is slow enough, the motor will remain in lock with the commutation (treating the BLDC like a stepper motor). This is referred to as "open loop control" in the application note. It will be used to test the basic order of PWM drive signals.

We will begin with very low voltage (i.e. low duty cycle) and investigate the lowest voltage that can support this open-loop driving method. We will then raise the RPM until the motor is unable to keep up with the open loop method (after this point, sensorless control will be required).

== Method

The intention is create simple breadboard-based hardware to drive the T-Motor P1604 3800KV motor. The electrical design of the motor driver can be optimised later; the main intention of this experiment is to test the feasibility of the software.

=== Hardware setup

Using the https://www.st.com/en/evaluation-tools/32f746gdiscovery.html[STM32F746-DISCO] board (because I have that lying around), following the design used in the https://www.st.com/en/evaluation-tools/b-g431b-esc1.html[B-G431B-ESC1] evaluation board.

This evaluation board uses the L638E high voltage high/low-side driver, up to 600V, \~ 50ns rise/fall with 1nF load, \~ 0.5A gate drive source/sink. Will replace with similar part IR2109PBF, which has a lower drive strength and slower switching time, but the through-hole version is available. Lower performance will produce a better lower bound on requirements if it works.

The evaluation board uses STL180N6F7 N-channel 60V, 1.9mOhm, 120A MOSFETs. We will replace with STP36NF06L, with reduced current to 30A (this is what is used in the reference Toothpick AIO design). It has an input capacitance of 600pF.

The following is the list of components required for the hardware setup:

* 1 x T-Motor P1604 3800KV motor (mounted in AOS 3.5 V5 Freestyle Quadcopter Frame for this experiment)
* 1 x STM32F746 DISCO board
* 1 x breadboard
* 3 x IR2109PBF half-bridge driver
* 6 x STP36NF06L MOSFETs

TODO: add a picture of the wiring.

=== Software setup

We will use this opportunity to try using Rust for something non-trivial with the STM32F7 series.

==== Getting basic PWM working

Although it is not clearly stated on the summary page of the STM32F746 datasheet, this MCU does have advanced control timers (TIM1 and TIM8). These timers have four channels, each of which has a positive and a complement pin (used for the high and low side of a half-H bridge). Three of these channels are suitable to drive a three-phase brushless motor.

A very quick test using the minimal project `pwm`, based on https://github.com/stm32-rs/stm32f7xx-hal/blob/main/examples/pwm.rs[this example], works on the STM32F746 DISCO board. The relevant lines to configure the PWM in Rust are:

[,rust]
----
// PA8 is pin 3 on CN7 on the Arduino header of the board. It
// corresponds to TIM1_CH1 (the into_alternate followed by passing
// it to the TIM1.pwm_hz() call configures the pin).
//
// PA9 is not mapped to any easily accessible pin on the DISCO board,
// but you can touch an oscilloscope probe on the SB13 bridge to see
// the signal
let gpioa = dp.GPIOA.split();
let channels = (gpioa.pa8.into_alternate(), gpioa.pa9.into_alternate());

let pwm = dp.TIM1.pwm_hz(channels, 20.kHz(), &clocks).split();
let (mut ch1, mut ch2) = pwm;

let max_duty = ch1.get_max_duty();
ch1.set_duty(max_duty / 2);
ch1.enable();

let max_duty = ch2.get_max_duty();
ch2.set_duty(max_duty / 4);
ch2.enable();
----

An immediate problem is the lack of conveniently-mapped pins on the DISCO board.

From the datasheet, the only timer channels with an easily accessible list of possible alternate pins for the 6 channels of TIM1, along with the pin use on the DISCO board, are:

* TIM1_CH1: PE9 (SDRAM use, data), PA8 (accessible pin header)
* TIM1_CH1N: PE8 (SDRAM use, data), PA7 (ETH use), PB13 (USB HS use)

* TIM1_CH2: PE11 (SDRAM use, data), PA9 (VCP_TX, part of ST-LINK circuit, SB13 jumper)
* TIM1_CH2N: TODO

* TIM1_CH3: PE13 (SDRAM use, data), PA10 (ID pin 4 of OTG FS, CN13)
* TIM1_CH3N: TODO

* TIM1_CH4: PE14 (SDRAM use, data), PA11 (DM pin 2 of OTG FS, CN13)
* TIM1_CH4N: TODO

From the data above, it is clear that TIM1 cannot be utilised without (probably) modifying the board (e.g. removing the SDRAM module). The same is true for TIM8, which is equally inaccessible. Testing the advanced timers is therefore out of scope for this first experiment.

The timer channels which are accessible on the headers are as follows:

* TIM12_CH1: PH6, pin7 CN4
* TIM12_CH2: PB15, pin 4 CN7
* TIM1_CH1: PA8, pin 3 CN7
* TIM2_CH1: PA15, pin 2 CN7
* TIM3_CH1: PB4, pin 4 CN4
* TIM5_CH4: PI0 (letter i, number zero), pin 6 CN4

Luckily, there are six timers here (these exhaust all the timers on the Arduino pin headers), so there is a possibility of three-phase motor control if the peripherals can be synchronised appropriately.

A snippet of the basic code required to turn on the channels is shown below:

[,rust]
----
// How to turn on one channel on a timer
// CN4, pin 4
let channels = gpiob.pb4.into_alternate();
let mut ch = dp.TIM3.pwm_hz(channels, 20.kHz(), &clocks).split();
let max_duty = ch.get_max_duty();
ch.set_duty(max_duty / 2);
ch.enable();

// How to turn on multiple channels in a timer
let channels = (gpioh.ph6.into_alternate(), gpiob.pb15.into_alternate());
let pwm = dp.TIM12.pwm_hz(channels, 20.kHz(), &clocks).split();
let (mut ch1 , mut ch2) = pwm;

// CN4, pin 7	
let max_duty = ch1.get_max_duty();
ch1.set_duty(max_duty / 4);
ch1.enable();	

// CN7, pin 4	
let max_duty = ch2.get_max_duty();
ch2.set_duty(max_duty / 7);
ch2.enable();
----

NOTE: incorrectly using these functions will result in a compile error (i.e. getting the tuples wrong or forgetting to call `split`), but attempting to map an invalid pin (i.e. one without the correct alternate function) will also result in a very similar-looking compile error. Watch out for the latter case.

This very simple exercise shows that naively enabling all the PWM channels produced PWM signals that are not synchronised (as expected). However, by moving all the enable signals into a block, the channels become very nearly synchronised:

[,rush]
----
ch0.enable();
ch1.enable();
ch2.enable();	
ch3.enable();
ch4.enable();
ch5.enable();
----

However, this synchronisation does not appear to survive optimisation (`cargo run --release`), and there is no guarantees on the synchronisation achieved like this.


== Results

== Conclusions
