= Basic Embedded Rust

Started: 15/07/2024
Finished: 

This experiment is about getting the basics working with Rust and the STM32F746 microcontroller on the DISCO board. We want to check that everything we want to do is easily possible:

* Compile and run
* Debug using a serial console
* Debug using breakpoints and a debugger
* Working with basic input/output
* Work with timers and interrupts
* Work with peripherals exposed through a HAL
* Work with peripherals that do not have a HAL library

If possible, we also want to find some options for RTOS or similar frameworks for structuring large or complicated programs with multiple concurrent tasks.

This page contains the notes relating to the points above. Most of the material is based on the https://docs.rust-embedded.org/book/[Embedded Rust Book], and links to other resources are provided as they are needed.

== Getting Started

This section contains the order I did things. To follow along and run all the examples, you need the STM32F746 Discovery board. Everything was tested on Linux Mint 21.1 Cinnamon.

. To get started, read the first few sections of the https://docs.rust-embedded.org/book/[Embedded Rust Book]. Notes on <<_setting_up_the_toolchain>>, <<_creating_a_new_project>>, <<_debugging>>, and <<_running_on_hardware>> are given below. These follow the Rust Embedded Book, and that should be used as the proper reference.
. Before starting to program the STM32F7 device seriously, get printing using semi-hosting and ITM working (which is the same as the Serial Wire Viewer, if you are familiar with the STM32CubeIDE). The <<_running_on_hardware>> section contains an example using semi hosting (which is convenient but slow), and the section <<_using_itm_serial_wire_viewer>> contains information on setting up ITM debugging. Also, try out the different panic handlers; once semi-hosting and ITM are working, it should be as simple as replacing one use statement at the top of the file.
. I found a combination of the Embedded Rust Book and https://dev.to/theembeddedrustacean/stm32f4-embedded-rust-at-the-hal-gpio-interrupts-e5[this blog series] a good starting point for embedded programming using the HAL. The blog targets STM32F4, but is easily converted to STM32F7. See the `basics/examples/button_led.rs` file for a basic example showing GPIO/delay usage. It is based on https://blog.theembeddedrustacean.com/stm32f4-embedded-rust-at-the-hal-gpio-button-controlled-blinking[this blog post].
. There are two main frameworks available for structuring embedded applications in Rust: https://rtic.rs/2/book/en/preface.html[RTIC] (previously known as RTFM) and https://embassy.dev/[Embassy]. Basic experiments with RTIC are described in <<_using_rtic>>

== Setting up the Toolchain

WARNING: These instructions were written on a computer that had many of the tools already installed. Need to come back to this with a fresh Ubuntu instance and tidy up the instructions.

Make sure Rust is installed first. Then run (these steps are explained in detail in the embedded Rust book):

[,bash]
----
# Cortex M7 with hardware floating point
# Adjust as required
rustup target add thumbv7em-none-eabihf

# Install LLVM-specific binutils (objdump, etc.)
cargo install cargo-binutils
rustup component add llvm-tools

# Install some Qemu tools and OpenOCD (a debugger)
sudo apt install gdb-arm-none-eabi openocd qemu-system-arm
----

To test OpenOCD, run:

[,bash]
----
# Plug in the STM32F746 DISCO board first
openocd -f interface/stlink.cfg -f target/stm32f7x.cfg
----

You should see a string of `Info` lines including something similar to: `Info : stm32f7x.cpu: hardware has 8 breakpoints, 4 watchpoints`. 

== Creating a New Project

The simplest way to create a new project for Cortex M series devices is to run:

[,bash]
----
cargo generate --git https://github.com/rust-embedded/cortex-m-quickstart
# When prompted, give the project a name (we chose "basics" in this folder)
----

Go into the folder and edit `Cargo.toml` and edit the details are required.

Open the `.cargo/config.toml` file and uncomment the correct line matching the target architecture of the STM32F746:

[,toml]
----
[build]
# Pick ONE of these default compilation targets
# target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"        # Cortex-M3
# target = "thumbv7em-none-eabi"       # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv8m.base-none-eabi"   # Cortex-M23
# target = "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
# target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)
----

== Running using QEMU

To run a binary on Qemu, first compile it. For example, to compile the `hello` example, run

[,bash]
----
cargo build --example hello
----

To run it with Qemu, run:

[,bash]
----
# Modify the -kernel argument to point to the binary to run.
# Take care that the -machine argument is an architecture that
# matches the one you compiled for (i.e. mps2-an500 is a Cortex-M7
# machine).
qemu-system-arm \
  -cpu cortex-m7 \
  -machine mps2-an500 \
  -nographic \
  -semihosting-config enable=on,target=native \
  -kernel target/thumbv7em-none-eabihf/debug/examples/hello
----

If it is successful, it should print `Hello, world!`. The source code is in `examples/hello.rs`.

Documentation for the ARM machines was obtained from https://www.qemu.org/docs/master/system/arm/mps2.html[here].

== Debugging

To debug using QEMU and gdb, add the `-gdb` flag to the QEMU command above:

[,bash]
----
qemu-system-arm \
  -cpu cortex-m7 \
  -machine mps2-an500 \
  -nographic \
  -semihosting-config enable=on,target=native \
  -gdb tcp::3333 \
  -S \
  -kernel target/thumbv7em-none-eabihf/debug/examples/hello
----

Next, open an interactive `gdb` prompt by running:

[,bash]
----
gdb-multiarch -q target/thumbv7em-none-eabihf/debug/examples/hello
----

Connect to the QEMU emulation and debug the program as follows:

[,bash]
----
# Connect to QEMU
target remote :3333

# Show the source for main
list main

# Add a breakpoint on a particular line of main
break 13

# Run the program to the breakpoint
continue

# Move through the program, skipping over subroutine calls
# (Use step to enter subroutines)
next
----

== Running on Hardware

Make sure the memory map is set up correctly for the DISCO board (`memory.x`):

[,linker]
----
MEMORY
{
  /* TODO: double check these values */
  FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 1024K
  RAM (xrw)  : ORIGIN = 0x20000000, LENGTH = 320K
}
----

Compile the program after modifying the memory map:

NOTE: Before compiling the `examples/hello.rs` example, comment out this line: `debug::exit(debug::EXIT_SUCCESS);`.

[,bash]
----
cargo clean # to ensure the memory.x change is not missed
cargo build --example hello
----

Next, modify the `openocd.cfg` file (generated by the template) and change `stm32f3.cfg` to `stm32f7.cfg`, to match the DISCO board.

To test that everything is working, run:

[,bash]
----
openocd
----

from the root project folder (next to `Cargo.toml`). It should start listening for gdb on port 3333.

Start gdb in the same way as debugging using QEMU:

[,bash]
----
gdb-multiarch -q target/thumbv7em-none-eabihf/debug/examples/hello
----

Connect to the openocd process, flash the program, and run as follows:

[,bash]
----
# Connect to openocd
target remote :3333

# Flash the binary to the device
load

# Enable semihosting
monitor arm semihosting enable

# Add a new breakpoint
break main

# Run the program to the breakpoint
continue

# Move through the program, skipping over subroutine calls
# (Use step to enter subroutines)
next
----

A more advanced version of this script is generated as part of the template, in `openocd.gdb`. To use it, run `openocd` first, and then run gdb as follows:

[,bash]
----
gdb-multiarch -x openocd.gdb target/thumbv7em-none-eabihf/debug/examples/hello
----

== Using ITM (Serial Wire Viewer)

ARM devices support a one-wire serial debug port via the SWO pin. An example is contained in the `examples/itm.rs` file.

To set up `openocd.gdb` to use ITM, ensure the following two lines are present:

[,bash]
----
# Ensure that the clock frequency here matches the
# system clock frequency configured in Rust
monitor tpiu config internal itm.txt uart off 80000000
monitor itm port 0 on
----

A minimal rust program to print to ITM is shown below:

[,rust]
----
#![no_std]
#![no_main]
use panic_halt as _;
use cortex_m::iprintln;
use cortex_m_rt::entry;
use stm32f7xx_hal as hal;
use stm32f7xx_hal::prelude::*;

#[entry]
fn main() -> ! {
    if let Some(dp) = hal::pac::Peripherals::take() {
        let rcc = dp.RCC.constrain();
	// Set the system clock frequency as below
	rcc.cfgr.sysclk(80_000_000.Hz()).freeze();
    }
    if let Some(mut cp) = cortex_m::peripheral::Peripherals::take() {
	let stim = &mut cp.ITM.stim[0];
	iprintln!(stim, "Hello World ITM!");
    }
    loop {}
}
----

Run the program by starting `openocd` (from the root crate directory) and then running `cargo run` (make sure cargo run is set up to run `gdb-multiarch -x openocd.gdb` first). After running the example (type `continue` in gdb), a file called `itm.txt` will be created, where ITM messages will be dumped. You can 

To read it, install `itmdump` using `cargo install itm`. Then run `itmdump -f itm.txt` to view the messages.

If the file is not present, check the `openocd.gdb` configuration is correct. If the file is present but empty, looks corrupt, or fails to parse using `itmdump`, double check that the clock frequency of the microcontroller matches the lines in `openocd.gdb`.

NOTE: You can use ITM and semi-hosting at the same time. You can also print panic messages over ITM using `use panic_itm as _`.

== Inspecting Compiled Code

This is a list of useful tips for looking at compiled code using cargo binutils.

To view the headers of the compiled executable for the project `basics`, run

[,bash]
----
# from the folder containing Cargo.toml
# Replace `basics` with project name
cargo readobj --bin basics -- --file-headers
----

Use `cargo size` to inspect the size of the sections in the executable, which reflects the size of the object that will be loaded onto the device:

[,bash]
----
# Replace `basics` with project name
cargo size --bin basics --release -- -A
----

To disassemble the binary, run:

[,bash]
----
# Replace `basics` with your project name
cargo objdump --bin basics --release -- --disassemble --no-show-raw-insn --print-imm-hex
----

== Using RTIC

https://rtic.rs/2/book/en/preface.html[RTIC] is an embedded software for structuring real-time applications made of multiple tasks. It is quite similar to an RTOS, but is oriented towards using the interrupt controller and interrupt priorities to hardware-schedule tasks, rather than having a software scheduler controlling threads.

This section follows the basic getting started guide https://rtic.rs/2/book/en/starting_a_project.html[here], which is based on the template https://github.com/rtic-rs/defmt-app-template[defmt-app-template].

To prepare, install some dependencies. This template uses https://probe.rs/[probe-rs], which is a replacement for the OpenOCD+gdb combination for flashing and running code on the hardware. https://github.com/knurling-rs/flip-link[Flip link] is a library for moving the stack to the bottom of the memory map to catch stack overflows safely.

[,bash]
----
# From the probe-rs main web page
curl --proto '=https' --tlsv1.2 -LsSf https://github.com/probe-rs/probe-rs/releases/latest/download/probe-rs-tools-installer.sh | sh

# Install flip-link
cargo install flip-link
----

Next, clone the template repository into your own directory:

[,bash]
----
git clone https://github.com/rtic-rs/app-template rtic-app
----

NOTE: If you are cloning this into your own git repository to use as part of your project, ensure you delete the `.git` folder to avoid any conflicts with your own repository. Similarly, consider deleting the `.gitignore`.

Now follow the instructions outlined in the https://github.com/rtic-rs/defmt-app-template[repo], briefly summarised here:

. Set the runner to `probe-rs run --chip STM32F746NGHx` in `.cargo/config.toml`
. Set the target to `"thumbv7em-none-eabihf"` in `.cargo/config.toml`
. If not done already, ensure the toolchain is installed: `rustup +nightly target add thumbv7em-none-eabihf`
. Set the correct RTIC backend: `rtic = { version = "2.0.0", features = [ "thumbv7-backend" ] }`
. Add the HAL into `Cargo.toml`:
+
[,toml]
----
[dependencies.stm32f7xx-hal]
version = "0.8.0"
features = ["stm32f746", "rt"]
----
. Import the HAL into the `rtic-app/src/lib.rs`: `use stm32f7xx_hal as _;`.
. Set the HAL and list of free interrupts in the `rtic::app` macro in `rtic-app/src/bin/minimal.rs`: `#[rtic::app(device = stm32f7xx_hal::pac, dispatchers = [TIM2])]`. See the list of STM32F7xx interrupts in the `stm32f7xx-hal::pac::Interrupt` enum https://docs.rs/stm32f7xx-hal/latest/stm32f7xx_hal/pac/enum.Interrupt.html[here]. These interrupts are associated to software tasks in the application.

The application should now build using `cargo build`. You can flash and run it (after connecting the DISCO board) by running:

[,bash]
----
# Add the DEFMT_LOG definition to show info messages.
# By default, defmt only shows error messages
DEFMT_LOG=info cargo rb minimal
----

Throughout the code, logging is achieved by `defmt` macros such as `defmt::info!("Hello, World!")`. How this is formatted on the host side is  documented https://defmt.ferrous-systems.com/custom-log-output[here], which lists format specifiers. These are passed to `probe-rs` (see https://defmt.ferrous-systems.com/custom-log-output#passing-log-format-to-printers[this section]), which is achieved by updating the `.config/cargo.toml`.

[,toml]
----
runner = [
       "probe-rs",
       "run",
       "--chip",
       "STM32F746NGHx",
       "--log-format",
       # This line prints the timestamp, followed by the
       # log type and the message itself
       "{t} {L} {s}"
]
----

Read through https://rtic.rs/2/book/en/by-example.html[the RTIC by Example documentation] for getting started information on how to use the framework.

=== Basics of tasks

Using the framework revolves around defining tasks tied to interrupts. Two tasks are always present, the `init` task and the `idle` task. The `init` task sets up the software system (clock configuration, interrupt configuration, etc.), and starts software tasks. The `idle` task runs when other tasks are not running.

All tasks in RTIC are tied to interrupts, but "software tasks" are not tied to the specific functionality of the interrupt. These tasks use any free interrupts that are not used for anything else in the program (these are listed in the `dispatchers` list in the `rtic::app` macro). Software tasks are spawned in the `init` task with a line like this: `task1::spawn().ok()`, and are declared like this:

[,rust]
----
// Software tasks are automatically mapped to interrupts listed
// in the dispatchers argument. These are interrupts you are not
// using for their actual hardware functionality.
#[rtic::app(device = stm32f7xx_hal::pac, dispatchers = [TIM2])]
mod app {

...

       // Start the software task in the `init`
       // task as follows.
       task1::spawn().ok();
       ...
    }


    // A software task has no binds argument in the task macro,
    // and is declared as async.
    #[task(priority = 1)]
    async fn task1(_cx: task1::Context) {
        defmt::info!("Hello from task1!");
    }

}
----

The `defmt-app-template` example `minimal.rs` uses a software task. Software tasks use `async`, are intended to be spawned once and run indefinitely (although they can `await`), do not have any explicit `binds` argument in the `task` macro, and must have a free (i.e. unused) interrupt listed in the `dispatchers`. Think of them as providing similar functionality to a thread in a normal RTOS. Read more about software threads in the https://rtic.rs/2/book/en/by-example/software_tasks.html[official RTIC documentation].

NOTE: Make sure that the interrupts being used for software tasks do not have side-effects, or other special purposes, and are not related to peripherals you need to use for their real functionality.

The software task in `minimal.rs` can be converted to a hardware task, which is a task specifically intended to run as an interrupt service routine (ISR). As described in the https://rtic.rs/2/book/en/by-example/hardware_tasks.html[documentation], this is intended to run to completion (it is not `async`, so no `await` statements), but it can be preempted. Use hardware tasks to respond to true peripheral interrupts, similarly to the use of an ISR in a regular RTOS.

To convert the software task to a hardware task, modify the code as follows:

[,rust]
----
// Make sure you remove any interrupts being used as hardware tasks
// (ISRs) from the dispatchers list.
#[rtic::app(device = stm32f7xx_hal::pac, dispatchers = [])]
mod app {

...

       // You can manually trigger a hardware interrupt as follows,
       // but more likely, you would configure the peripheral
       // responsible for the interrupt and let it trigger in
       // response to whatever event it is linked to.
       rtic::pend(Interrupt::TIM2);

       ...
    }


    // A hardware interrupt is just like a regular ISR. Specify the
    // interrupt using the binds argument, and remove the async
    // keyword (hardware tasks cannot await).
    #[task(binds = TIM2, priority = 1)]
    fn task1(_cx: task1::Context) {
        defmt::info!("Hello from task1!");
    }

}
----

=== DISCO Board Serial (USART1)

The STM32F746 DISCO board does not have many buttons, so taking commands via the ST-LINK v2 serial interface is a good way to add a lot of flexibility.

NOTE: The built-in serial conenction via ST-LINK v2 is nothing to do with debugging, gdb, openocd, probe-rs, or the like. It is accessible via a regular Linux virtual terminal `/dev/ttyACM0` while the device is connected and the program is running.

Referring to the DISCO board link:../../reference/schematic-stm32f746g-disco.pdf[schematic], the ST-LINK v2 virtual com port (`VCP-RX` and `VCP-TX`) is connected to `PB7` and `PA9`, which corresponds to `USART1` on the microcontroller.

To configure the peripheral, using the following code in the `init` task, after setting up clocks:

[,rust]
----
let gpioa = device.GPIOA.split();
let gpiob = device.GPIOB.split();

let tx = gpioa.pa9.into_alternate();
let rx = gpiob.pb7.into_alternate();

let mut serial = Serial::new(
    device.USART1,
    (tx, rx),
    &clocks,
    serial::Config {
	// Default to 115_200 bauds
	..Default::default()
    },
);

// Listen for a received character. Make sure you write an RTIC
// hardware task that binds to the `USART1` interrupt.
serial.listen(serial::Event::Rxne);

let (tx, rx) = serial.split();

...

// At the end, return the rx and tx as local resources
(Shared {}, Local { tx, rx })
----

This configures the HAL serial interface, and then makes the `Rx<USART1>` and `Tx<USART1>` variables that can be stored in the local struct:

[,rust]
----
#[local]
struct Local {
    tx: serial::Tx<USART1>,
    rx: serial::Rx<USART1>,
}
----

Finally, add a hardware task for the USART1 interrupt:

[,rust]
----
// This task echos received characters back to the host
#[task(binds = USART1, priority = 1, local=[tx, rx])]
fn serial_task(cx: serial_task::Context) {
    let received = cx.local.rx.read().unwrap_or('E' as u8);
    cx.local.tx.write(received).ok();
}
----

On the Linux side, the STM32F746 DISCO board ST-LINK v2 is exposed as the device `/dev/ttyACM0`. You can connect to it by running `sudo apt install cu`, and then:

[,bash]
----
# Before running this, connect the DISCO board and run `cargo rb minimal`
cu -l /dev/ttyACM0 -s 115200
----

To exit, type `~.`. 

== General Rust Notes

This section contains a set of miscellaneous notes relating to Rust code/projects that may be helpful.

=== Dependency version issues

Dependencies are declared in `Cargo.toml` with version numbers, but problems can arise when you declare a crate dependency, and so does one of the other crates you are using. This can produce compilation issues due to mismatched types or traits, and can be hard to debug

For example, suppose the `stm32f7xx-hal` crate v0.7 is used, and so is the `cortex-m` crate v0.6.0. This produces an inconsistency, because the `stm32f7xx-hal` crate uses `cortex-m` v0.7.7 internally. This produces the error `the trait Nr is not implemented for `stm32f7xx_hal::interrupt``, on the following code:

[,rust]
----
unsafe {
    cortex_m::peripheral::NVIC::unmask(Interrupt::TIM2);
}
----

NOTE: This specific problem is documented https://dev.to/theembeddedrustacean/stm32f4-embedded-rust-at-the-hal-gpio-interrupts-e5[here]. 

To fix the problem, ensure that crate version are consistent. You can use `cargo tree` to view the crate versions used in your project. The issue can arise if you copy and pasted code into your `Cargo.toml` from old source (with out-of-date crate versions), or you have updated one crate without updating others.

You can also avoid the problem by using the version of the crate exposed by your other dependency, and not declaring it as a dependency yourself. For example, you can access `cortex-m` through the `stm32f7xx-hal` crate.

When I had this problem, I fixed it by changing `stm32f7xx-hal` to v0.8.0, and changing `cortex-m` to v0.7.7 (both the latest versions).
